### ISSUE TITLE
Do not use LDFLAGS for library inclusion

### ISSUE THREAD

**Issue by mkszuba** [steelman/xystray#1]
Hello,

In the current version of the Makefile the linker is told to link xystray against libX11 and libXt by using the variable LDFLAGS, which is set unconditionally. This is not optimal because it prevents the user from using their own LDFLAGS from the environment, which one might do e.g. in order to enable LTO. I would recommend making it possible to override LDFLAGS by the environment, and in order for that not to break the build process by clobbering your own command line specifying libraries in a separate variable such as LIBS.

One way of achieving this:

https://github.com/mkszuba/gentoo/blob/xystray/x11-misc/xystray/files/xystray-1.0-ldflags.patch

**Comment by steelman** [comment]
404 (no branch)

OK, it's here

https://github.com/mkszuba/gentoo/blob/master/x11-misc/xystray/files/xystray-1.0-ldflags.patch

Seems reasonable.

**Comment by doughdemon** [comment]
In order to fix https://bugs.gentoo.org/show_bug.cgi?id=581192, please put $(LIBS) after all other options.

**Comment by steelman** [comment]
I'll push as soon as Toralf Förster confirms.
